Update evaluator

diff --git a/evaluate_shell b/evaluate_shell
--- a/evaluate_shell
+++ b/evaluate_shell
@@ -1,13 +1,28 @@
-mapfile -t codes < <(git -C "${user_repo}" diff HEAD..HEAD~1 --name-only)
+mapfile -t files < <(git -C "${user_repo}" diff HEAD..HEAD~1 --name-only)
 
 add_badge() {
   printf '%s: %s\n' "${1}" "${2}" >> "${BADGES_TXT}"
 }
+err() {
+  printf '%s[error]: %s\n' "$*" >&2
+}
+check_x() {
+  [[ -x "${1}" ]] \
+    || chmod +x "${1}"
+}
 
-for code in "${codes[@]}"; do
-  printf '%s\n' "Evaluating '${code}' ..."
-  "$code"
-  add_badge "${code}" "${?}"
+for file in "${files[@]}"; do
+  printf '%s\n' "Running '${file}' ..."
+  check_x "${file}"
+  case "${file}" in
+    status/*)
+      "$code" < status/rz_dispatcher.log
+      ;;
+    *)
+      "$code"
+  esac
+  #printf '%s\n' "Evaluating '${file}' ..."
+  add_badge "${file}" "${?}"
 done
 
 # declare -r BADGES_TXT="${RESULTS}/badges.txt"
