Refactor ams to academy

diff --git a/gitlab-stages.yml b/gitlab-stages.yml
--- a/gitlab-stages.yml
+++ b/gitlab-stages.yml
@@ -7,17 +7,17 @@
   # set git user
   git config --global user.email "${GITLAB_USER_EMAIL}"
   git config --global user.name "Runner = ${CI_RUNNER_DESCRIPTION}"
-  export AMS_DIR="$(mktemp -d)"
+  export ACADEMY_DIR="$(mktemp -d)"
   revision=$(grep -oP "[^/]+(?=/gitlab-stages)" .gitlab-ci.yml)
-  git clone --single-branch --branch ${revision} https://github.com/InternetGuru/ams ${AMS_DIR}
+  git clone --single-branch --branch ${revision} https://github.com/InternetGuru/academy ${ACADEMY_DIR}
   # e.g. /umiami/george/csc220
   declare -r namespace="$(dirname "${PWD}" | cut -d/ -f3-)"
   declare -r project_name="$(basename "${PWD}")"
   # simplify project remote url
   git remote set-url --push origin "${namespace}/${project_name}.git"
   # set permissions
-  AMS=${AMS_DIR}/ams
-  chmod +x ${AMS_DIR}/*
+  ACADEMY=${ACADEMY_DIR}/academy
+  chmod +x ${ACADEMY_DIR}/*
 
 .before_script_token: &validate_token |
   # prepare acccess token for the distribution script
@@ -62,36 +62,36 @@ collect:
     - echo "${ACCESS_TOKEN}" > ${HOME}/.gitlab_access_token
     # process files distributed from current branch
     - declare user_namespace="${namespace}/${CI_COMMIT_REF_NAME}"
-    # checkout to AMS_SOLUTION branch
+    # checkout to ACADEMY_SOLUTION branch
     - |
-        if [[ -z "${AMS_SOLUTION}" ]]; then
-          AMS_SOLUTION='master'
+        if [[ -z "${ACADEMY_SOLUTION}" ]]; then
+          ACADEMY_SOLUTION='master'
         fi
         git fetch --all
-        git checkout "${AMS_SOLUTION}"
+        git checkout "${ACADEMY_SOLUTION}"
     # prepare deadline and editable options
     - declare deadline=''
     - declare editable=''
     - |
-        if [[ -n "${AMS_DEADLINE}" ]]; then
-          deadline="--deadline '${AMS_DEADLINE}'"
+        if [[ -n "${ACADEMY_DEADLINE}" ]]; then
+          deadline="--deadline '${ACADEMY_DEADLINE}'"
         fi
-        if [[ -n "${AMS_EDITABLE}" ]]; then
-          editable="--editable '${AMS_EDITABLE}'"
+        if [[ -n "${ACADEMY_EDITABLE}" ]]; then
+          editable="--editable '${ACADEMY_EDITABLE}'"
         fi
     # run collect for given or all branches
     - mkdir -p '.collect'
     - |
-        ${AMS} collect ${deadline} ${editable} \
+        ${ACADEMY} collect ${deadline} ${editable} \
         --namespace "${user_namespace}" --prefix "${project_name}-" \
         --output-dir '.collect' | tee 'summary.txt'
     # output variables and summary
     - mv 'summary.txt' '.collect/'
     - |
       echo '#######################'
-      echo "AMS_DEADLINE: '${AMS_DEADLINE}'"
-      echo "AMS_EDITABLE: '${AMS_EDITABLE}'"
-      echo "AMS_SOLUTION: '${AMS_SOLUTION}'"
+      echo "ACADEMY_DEADLINE: '${ACADEMY_DEADLINE}'"
+      echo "ACADEMY_EDITABLE: '${ACADEMY_EDITABLE}'"
+      echo "ACADEMY_SOLUTION: '${ACADEMY_SOLUTION}'"
       echo "summary.txt: ${CI_PROJECT_URL}/-/jobs/${CI_JOB_ID}/artifacts/raw/.collect/summary.txt"
       echo '#######################'
   when: manual
@@ -110,13 +110,13 @@ evaluate:
     paths:
       - target/
   script:
-    - ${AMS} evaluate
+    - ${ACADEMY} evaluate
   artifacts:
     paths:
       - .results/
     expire_in: 1 year
   rules:
-    - if: '$AMS_EVALUATE == "always"'
+    - if: '$ACADEMY_EVALUATE == "always"'
       when: always
     - when: manual
 
@@ -133,13 +133,13 @@ distribute:
     - declare -r branch="$(git rev-parse --abbrev-ref HEAD)"
     # set token file (will be deprecated)
     - echo "${ACCESS_TOKEN}" > ${HOME}/.gitlab_access_token
-    - mv "AMS_USERS" .. 2>/dev/null || true
+    - mv "ACADEMY_USERS" .. 2>/dev/null || true
     # distribute current project among all users
     - |
-        ${AMS} distribute --update-links --namespace "${namespace}/${branch}" \
-        --process-issues "${AMS_ISSUES:-${CI_COMMIT_REF_NAME}}" \
+        ${ACADEMY} distribute --update-links --namespace "${namespace}/${branch}" \
+        --process-issues "${ACADEMY_ISSUES:-${CI_COMMIT_REF_NAME}}" \
         --prefix "${project_name}-" \
-        <<< "$({ echo "${AMS_USERS:-${GITLAB_USER_NAME}}"; cat '../AMS_USERS' 2>/dev/null; } | tr ',' ' ')"
+        <<< "$({ echo "${ACADEMY_USERS:-${GITLAB_USER_NAME}}"; cat '../ACADEMY_USERS' 2>/dev/null; } | tr ',' ' ')"
   when: manual
 
 measure:
@@ -152,8 +152,8 @@ measure:
     - *global_init
   script:
     - |
-        if [[ -z "${AMS_MOSSURL}" ]]; then
-          echo "Missing AMS_MOSSURL"
+        if [[ -z "${ACADEMY_MOSSURL}" ]]; then
+          echo "Missing ACADEMY_MOSSURL"
           exit 1
         fi
     # set token file (will be deprecated)
@@ -161,19 +161,19 @@ measure:
     # process files distributed from current branch
     - declare -r user_namespace="${namespace}/${CI_COMMIT_REF_NAME}"
     # download moss script
-    - curl -o /usr/local/bin/moss "${AMS_MOSSURL}"
+    - curl -o /usr/local/bin/moss "${ACADEMY_MOSSURL}"
     - chmod +x /usr/local/bin/moss
     - export PATH="${PATH}:/usr/local/bin/"
     # create output directory
     - declare -r measure_output=".measure/${project_name}"
     - mkdir -p "${measure_output}"
-    # copy files from AMS_SOLUTION branch to measure
+    # copy files from ACADEMY_SOLUTION branch to measure
     - |
-        if [[ -z "${AMS_SOLUTION}" ]]; then
-          AMS_SOLUTION='master'
+        if [[ -z "${ACADEMY_SOLUTION}" ]]; then
+          ACADEMY_SOLUTION='master'
         fi
         git fetch --all
-        git --work-tree="${measure_output}" checkout -f "origin/${AMS_SOLUTION}" -- .
+        git --work-tree="${measure_output}" checkout -f "origin/${ACADEMY_SOLUTION}" -- .
     # run measure for given or all branches
-    - ${AMS} measure --output-dir "${measure_output}" --namespace "${user_namespace}" --prefix "${project_name}-"
+    - ${ACADEMY} measure --output-dir "${measure_output}" --namespace "${user_namespace}" --prefix "${project_name}-"
   when: manual
