Check ACADEMY_SUBMIT_TOKEN exists

diff --git a/submit b/submit
--- a/submit
+++ b/submit
@@ -5,6 +5,11 @@ if [[ -z "${ACADEMY_EDITABLE}" ]]; then
   exit 1
 fi
 
+if [[ -z "${ACADEMY_SUBMIT_TOKEN}" ]]; then
+  echo "Missing ACADEMY_SUBMIT_TOKEN variable or token"
+  exit 1
+fi
+
 # set url with token
 declare git_url
 git_url="https://project_${CI_PROJECT_ID}_bot:${ACADEMY_SUBMIT_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git"
@@ -22,6 +27,7 @@ git merge --no-ff --strategy-option theirs source
 # copy editable files from main
 # shellcheck disable=SC2086
 rm ${ACADEMY_EDITABLE}
+# shellcheck disable=SC2086
 git checkout main -- ${ACADEMY_EDITABLE} 2>/dev/null
 # rm .results (clean mess)
 rm -rf .results/
